
import "./globals.css";
import { Kalam } from "next/font/google";

const kalam = Kalam({
  variable: "--font-kalam",
  subsets: ["latin"],
  weight: ["300", "400", "700"],
});


export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className={kalam.variable}>
           <body className="font-kalam antialiased">{children}</body> 
    </html>
  );
}
